In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("Walmart_clean_data.csv")

In [6]:
unit_price_arr = df['unit_price'].to_numpy()
quantity_arr = df['quantity'].to_numpy()

print("Quantity array sample:", quantity_arr[:10])


Quantity array sample: [ 7.  5.  7.  8.  7.  7.  6. 10.  2.  3.]


# Square each quantity using NumPy

In [7]:
quantity_squared = quantity_arr ** 2
print(quantity_squared[:10])


[ 49.  25.  49.  64.  49.  49.  36. 100.   4.   9.]


# Find max, min, sum using NumPy

In [8]:
print("Max quantity:", np.max(quantity_arr))
print("Min quantity:", np.min(quantity_arr))
print("Total quantity sold:", np.sum(quantity_arr))


Max quantity: 10.0
Min quantity: 1.0
Total quantity sold: 23483.0


# Filter values using NumPy condition
find all unit prices > 50

In [9]:
high_prices = unit_price_arr[unit_price_arr > 50]
print(high_prices[:10])


[74.69 58.22 86.31 85.39 68.84 73.56 54.84 71.38 93.72 68.93]


# Compute correlation between two columns using NumPy
unit price vs quantity

In [10]:
corr = np.corrcoef(unit_price_arr, quantity_arr)
print("Correlation matrix:\n", corr)


Correlation matrix:
 [[1.         0.06178874]
 [0.06178874 1.        ]]


# Convert quantity to a NumPy array

In [11]:
quantity_arr = df['quantity'].to_numpy()
print(quantity_arr[:10])


[ 7.  5.  7.  8.  7.  7.  6. 10.  2.  3.]


In [12]:
import numpy as np

for col in ['unit_price', 'quantity', 'rating', 'Total']:
    data = df[col]
    print(f"\n--- {col.upper()} Statistics ---")
    print(f"Mean: {np.mean(data):.2f}")
    print(f"Median: {np.median(data):.2f}")
    print(f"Std Dev: {np.std(data):.2f}")
    print(f"25th Percentile: {np.percentile(data, 25):.2f}")
    print(f"75th Percentile: {np.percentile(data, 75):.2f}")



--- UNIT_PRICE Statistics ---
Mean: 50.62
Median: 51.00
Std Dev: 21.20
25th Percentile: 32.00
75th Percentile: 69.00

--- QUANTITY Statistics ---
Mean: 2.36
Median: 2.00
Std Dev: 1.61
25th Percentile: 1.00
75th Percentile: 3.00

--- RATING Statistics ---
Mean: 5.83
Median: 6.00
Std Dev: 1.76
25th Percentile: 4.00
75th Percentile: 7.00

--- TOTAL Statistics ---
Mean: 121.35
Median: 88.00
Std Dev: 112.67
25th Percentile: 54.00
75th Percentile: 156.00
